#1、Hysteria2 的 HTTP/3 配置示例
listen: :443 #HTTP/3 监听端口
tls:
  cert: /home/tls/xx.yy/xx.yy.crt #换成自己的证书，绝对路径。
  key: /home/tls/xx.yy/xx.yy.key #换成自己的密钥，绝对路径。
auth:
  type: password #单用户密码验证模式。若使用多用户密码验证模式，请参考官方示例调整。
  password: 123a65h7890 #单用户验证密码，修改为自己的。
masquerade:
  type: file #配置静态文件服务器。若配置反向代理，请参考官方示例调整。
  file:
    dir: /var/www/html #修改为自己存放的 WEB 文件路径
#备注：本示例仅共用 TCP/UDP 443 端口推荐，即 Hysteria2 使用 UDP 443 端口，其它应用使用 TCP 443 端口。


#2、Hysteria2 的混淆配置示例
listen: :2083 #UDP 监听端口
tls:
  cert: /home/tls/xx.yy/xx.yy.crt #换成自己的证书，绝对路径。
  key: /home/tls/xx.yy/xx.yy.key #换成自己的密钥，绝对路径。
obfs:
  type: salamander
  salamander:
    password: 3452e3b8k2 #混淆密码，修改为自己的。
auth:
  type: password #单用户密码验证模式。若使用多用户密码验证模式，请参考官方示例调整。
  password: 123a65h7890 #单用户验证密码，修改为自己的。
#备注：
#1、如果 UDP 443 端口已被 NaiveProxy 的 HTTP/3 代理应用占用，推荐使用本示例来解决。
#2、如果你的网络针对性屏蔽了 QUIC 或 HTTP/3 流量（但允许其他 UDP 流量），可使用本示例来解决。
